void setup() {
  pinMode(9, OUTPUT);
  pinMode(10, OUTPUT);
  pinMode(11, OUTPUT);
  pinMode(12, OUTPUT);
  pinMode(13, OUTPUT);
}

void loop() {
  digitalWrite(9, HIGH); //FIRST SERIES
  delay(500);
  digitalWrite(9, LOW);
  digitalWrite(10, HIGH);
  delay(500);
  digitalWrite(10, LOW);
  digitalWrite(11, HIGH);
  delay(500);
  digitalWrite(11, LOW);
  digitalWrite(12, HIGH);
  delay(500);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(500);
  digitalWrite(13, LOW);
  delay(500);
  digitalWrite(13, HIGH);
  delay(500);
  digitalWrite(13, LOW);
  digitalWrite(12, HIGH);
  delay(500);
  digitalWrite(12, LOW);
  digitalWrite(11, HIGH);
  delay(500);
  digitalWrite(11, LOW);
  digitalWrite(10, HIGH);
  delay(500);
  digitalWrite(10, LOW);
  digitalWrite(9, HIGH);
  delay(500);
  digitalWrite(9, LOW); //FIRST SERIES END
  delay(500);
  digitalWrite(9, HIGH); //SECOND SERIES
  delay(250);
  digitalWrite(9, LOW);
  digitalWrite(10, HIGH);
  delay(250);
  digitalWrite(10, LOW);
  digitalWrite(11, HIGH);
  delay(250);
  digitalWrite(11, LOW);
  digitalWrite(12, HIGH);
  delay(250);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(250);
  digitalWrite(13, LOW);
  delay(250);
  digitalWrite(13, HIGH);
  delay(250);
  digitalWrite(13, LOW);
  digitalWrite(12, HIGH);
  delay(250);
  digitalWrite(12, LOW);
  digitalWrite(11, HIGH);
  delay(250);
  digitalWrite(11, LOW);
  digitalWrite(10, HIGH);
  delay(250);
  digitalWrite(10, LOW);
  digitalWrite(9, HIGH);
  delay(250);
  digitalWrite(9, LOW); //SECOND SERIES END
  delay(250);
  digitalWrite(9, HIGH); //THIRD SERIES
  delay(125);
  digitalWrite(9, LOW);
  digitalWrite(10, HIGH);
  delay(125);
  digitalWrite(10, LOW);
  digitalWrite(11, HIGH);
  delay(125);
  digitalWrite(11, LOW);
  digitalWrite(12, HIGH);
  delay(125);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(125);
  digitalWrite(13, LOW);
  delay(125);
  digitalWrite(13, HIGH);
  delay(125);
  digitalWrite(13, LOW);
  digitalWrite(12, HIGH);
  delay(125);
  digitalWrite(12, LOW);
  digitalWrite(11, HIGH);
  delay(125);
  digitalWrite(11, LOW);
  digitalWrite(10, HIGH);
  delay(125);
  digitalWrite(10, LOW);
  digitalWrite(9, HIGH);
  delay(125);
  digitalWrite(9, LOW); //THIRD SERIES END
  delay(350);
  digitalWrite(11, HIGH); //FOURTH SERIES
  delay(500);
  digitalWrite(11, LOW);
  digitalWrite(10, HIGH);
  digitalWrite(12, HIGH);
  delay(500);
  digitalWrite(10, LOW);
  digitalWrite(12, LOW);
  digitalWrite(9, HIGH);
  digitalWrite(13, HIGH);
  delay(500);
  digitalWrite(9, LOW);
  digitalWrite(13, LOW);
  delay(500);
  digitalWrite(9, HIGH);
  digitalWrite(13, HIGH);
  delay(500);
  digitalWrite(9, LOW);
  digitalWrite(13, LOW);
  digitalWrite(10, HIGH);
  digitalWrite(12, HIGH);
  delay(500);
  digitalWrite(10, LOW);
  digitalWrite(12, LOW);
  digitalWrite(11, HIGH);
  delay(500);
  digitalWrite(11, LOW); //FOURTH SERIES END
  delay(500);
  digitalWrite(11, HIGH); //FIFTH SERIES
  delay(250);
  digitalWrite(11, LOW);
  digitalWrite(10, HIGH);
  digitalWrite(12, HIGH);
  delay(250);
  digitalWrite(10, LOW);
  digitalWrite(12, LOW);
  digitalWrite(9, HIGH);
  digitalWrite(13, HIGH);
  delay(250);
  digitalWrite(9, LOW);
  digitalWrite(13, LOW);
  delay(250);
  digitalWrite(9, HIGH);
  digitalWrite(13, HIGH);
  delay(250);
  digitalWrite(9, LOW);
  digitalWrite(13, LOW);
  digitalWrite(10, HIGH);
  digitalWrite(12, HIGH);
  delay(250);
  digitalWrite(10, LOW);
  digitalWrite(12, LOW);
  digitalWrite(11, HIGH);
  delay(250);
  digitalWrite(11, LOW); //FIFTH SERIES END
  delay(250);
  digitalWrite(11, HIGH); //SIXTH SERIES
  delay(125);
  digitalWrite(11, LOW);
  digitalWrite(10, HIGH);
  digitalWrite(12, HIGH);
  delay(125);
  digitalWrite(10, LOW);
  digitalWrite(12, LOW);
  digitalWrite(9, HIGH);
  digitalWrite(13, HIGH);
  delay(125);
  digitalWrite(9, LOW);
  digitalWrite(13, LOW);
  delay(125);
  digitalWrite(9, HIGH);
  digitalWrite(13, HIGH);
  delay(125);
  digitalWrite(9, LOW);
  digitalWrite(13, LOW);
  digitalWrite(10, HIGH);
  digitalWrite(12, HIGH);
  delay(125);
  digitalWrite(10, LOW);
  digitalWrite(12, LOW);
  digitalWrite(11, HIGH);
  delay(125);
  digitalWrite(11, LOW); //SIXTH SERIES END
  delay(350);
  digitalWrite(9, HIGH); //SEVENTH SERIES
  digitalWrite(10, HIGH);
  delay(500);
  digitalWrite(9, LOW);
  digitalWrite(10, LOW);
  digitalWrite(10, HIGH);
  digitalWrite(11, HIGH);
  delay(500);
  digitalWrite(10, LOW);
  digitalWrite(11, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(12, HIGH);
  delay(500);
  digitalWrite(11, LOW);
  digitalWrite(12, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, HIGH);
  delay(500);
  digitalWrite(12, LOW);
  digitalWrite(13, LOW);
  delay(500);
  digitalWrite(13, HIGH);
  digitalWrite(12, HIGH);
  delay(500);
  digitalWrite(13, LOW);
  digitalWrite(12, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(11, HIGH);
  delay(500);
  digitalWrite(12, LOW);
  digitalWrite(11, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(10, HIGH);
  delay(500);
  digitalWrite(11, LOW);
  digitalWrite(10, LOW);
  digitalWrite(10, HIGH);
  digitalWrite(9, HIGH);
  delay(500);
  digitalWrite(10, LOW);
  digitalWrite(9, LOW); //SEVENTH SERIES END
  delay(500);
  digitalWrite(9, HIGH); //EIGHTH SERIES
  digitalWrite(10, HIGH);
  delay(250);
  digitalWrite(9, LOW);
  digitalWrite(10, LOW);
  digitalWrite(10, HIGH);
  digitalWrite(11, HIGH);
  delay(250);
  digitalWrite(10, LOW);
  digitalWrite(11, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(12, HIGH);
  delay(250);
  digitalWrite(11, LOW);
  digitalWrite(12, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, HIGH);
  delay(250);
  digitalWrite(12, LOW);
  digitalWrite(13, LOW);
  delay(250);
  digitalWrite(13, HIGH);
  digitalWrite(12, HIGH);
  delay(250);
  digitalWrite(13, LOW);
  digitalWrite(12, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(11, HIGH);
  delay(250);
  digitalWrite(12, LOW);
  digitalWrite(11, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(10, HIGH);
  delay(250);
  digitalWrite(11, LOW);
  digitalWrite(10, LOW);
  digitalWrite(10, HIGH);
  digitalWrite(9, HIGH);
  delay(250);
  digitalWrite(10, LOW);
  digitalWrite(9, LOW); //EIGHTH SERIES END
  delay(250);
  digitalWrite(9, HIGH); //NINTH SERIES
  digitalWrite(10, HIGH);
  delay(125);
  digitalWrite(9, LOW);
  digitalWrite(10, LOW);
  digitalWrite(10, HIGH);
  digitalWrite(11, HIGH);
  delay(125);
  digitalWrite(10, LOW);
  digitalWrite(11, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(12, HIGH);
  delay(125);
  digitalWrite(11, LOW);
  digitalWrite(12, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, HIGH);
  delay(125);
  digitalWrite(12, LOW);
  digitalWrite(13, LOW);
  delay(125);
  digitalWrite(13, HIGH);
  digitalWrite(12, HIGH);
  delay(125);
  digitalWrite(13, LOW);
  digitalWrite(12, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(11, HIGH);
  delay(125);
  digitalWrite(12, LOW);
  digitalWrite(11, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(10, HIGH);
  delay(125);
  digitalWrite(11, LOW);
  digitalWrite(10, LOW);
  digitalWrite(10, HIGH);
  digitalWrite(9, HIGH);
  delay(125);
  digitalWrite(10, LOW);
  digitalWrite(9, LOW); //NINTH SERIES END
  delay(350);
  digitalWrite(9, HIGH); //TENTH SERIES
  digitalWrite(11, HIGH);
  delay(500);
  digitalWrite(9, LOW);
  digitalWrite(11, LOW);
  digitalWrite(10, HIGH);
  digitalWrite(12, HIGH);
  delay(500);
  digitalWrite(10, LOW);
  digitalWrite(12, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(500);
  digitalWrite(11, LOW);
  digitalWrite(13, LOW);
  delay(500);
  digitalWrite(13, HIGH);
  digitalWrite(11, HIGH);
  delay(500);
  digitalWrite(13, LOW);
  digitalWrite(11, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(10, HIGH);
  delay(500);
  digitalWrite(12, LOW);
  digitalWrite(10, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(9, HIGH);
  delay(500);
  digitalWrite(11, LOW);
  digitalWrite(9, LOW); //TENTH SERIES END
  delay(500);
  digitalWrite(9, HIGH); //ELEVENTH SERIES
  digitalWrite(11, HIGH);
  delay(250);
  digitalWrite(9, LOW);
  digitalWrite(11, LOW);
  digitalWrite(10, HIGH);
  digitalWrite(12, HIGH);
  delay(250);
  digitalWrite(10, LOW);
  digitalWrite(12, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(250);
  digitalWrite(11, LOW);
  digitalWrite(13, LOW);
  delay(250);
  digitalWrite(13, HIGH);
  digitalWrite(11, HIGH);
  delay(250);
  digitalWrite(13, LOW);
  digitalWrite(11, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(10, HIGH);
  delay(250);
  digitalWrite(12, LOW);
  digitalWrite(10, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(9, HIGH);
  delay(250);
  digitalWrite(11, LOW);
  digitalWrite(9, LOW); //ELEVENTH SERIES END
  delay(250);
  digitalWrite(9, HIGH); //TWELFTH SERIES
  digitalWrite(11, HIGH);
  delay(125);
  digitalWrite(9, LOW);
  digitalWrite(11, LOW);
  digitalWrite(10, HIGH);
  digitalWrite(12, HIGH);
  delay(125);
  digitalWrite(10, LOW);
  digitalWrite(12, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(13, HIGH);
  delay(125);
  digitalWrite(11, LOW);
  digitalWrite(13, LOW);
  delay(125);
  digitalWrite(13, HIGH);
  digitalWrite(11, HIGH);
  delay(125);
  digitalWrite(13, LOW);
  digitalWrite(11, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(10, HIGH);
  delay(125);
  digitalWrite(12, LOW);
  digitalWrite(10, LOW);
  digitalWrite(11, HIGH);
  digitalWrite(9, HIGH);
  delay(125);
  digitalWrite(11, LOW);
  digitalWrite(9, LOW); //TWELFTH SERIES END
  delay(350);
  digitalWrite(9,HIGH); //THIRTEENTH SERIES
  digitalWrite(10,HIGH);
  digitalWrite(11,HIGH);
  digitalWrite(12,HIGH);
  digitalWrite(13,HIGH);
  delay(500);
  digitalWrite(9,LOW);
  digitalWrite(10,LOW);
  delay(500);
  digitalWrite(12,LOW);
  digitalWrite(13,LOW);
  delay(500);
  digitalWrite(11,LOW);
  delay(500);
  digitalWrite(9,HIGH);
  digitalWrite(10,HIGH);
  digitalWrite(11,HIGH);
  digitalWrite(12,HIGH);
  digitalWrite(13,HIGH);
  delay(500);
  digitalWrite(12,LOW);
  digitalWrite(13,LOW);
  delay(500);
  digitalWrite(9,LOW);
  digitalWrite(10,LOW);
  delay(500);
  digitalWrite(11,LOW);
  delay(500);
  digitalWrite(9,HIGH);
  digitalWrite(10,HIGH);
  digitalWrite(11,HIGH);
  digitalWrite(12,HIGH);
  digitalWrite(13,HIGH);
  delay(500);
  digitalWrite(11,LOW);
  delay(500);
  digitalWrite(9,LOW);
  digitalWrite(10,LOW);
  delay(500);
  digitalWrite(12,LOW);
  digitalWrite(13,LOW);
  delay(500);
  digitalWrite(9,HIGH);
  digitalWrite(10,HIGH);
  digitalWrite(11,HIGH);
  digitalWrite(12,HIGH);
  digitalWrite(13,HIGH);
  delay(500);
  digitalWrite(11,LOW);
  delay(500);
  digitalWrite(12,LOW);
  digitalWrite(13,LOW);
  delay(500);
  digitalWrite(9,LOW);
  digitalWrite(10,LOW); //THIRTEENTH SERIES END
  delay(500);
  digitalWrite(9,HIGH); //FOURTEENTH SERIES
  digitalWrite(10,HIGH);
  digitalWrite(11,HIGH);
  digitalWrite(12,HIGH);
  digitalWrite(13,HIGH);
  delay(250);
  digitalWrite(9,LOW);
  digitalWrite(10,LOW);
  delay(250);
  digitalWrite(12,LOW);
  digitalWrite(13,LOW);
  delay(250);
  digitalWrite(11,LOW);
  delay(250);
  digitalWrite(9,HIGH);
  digitalWrite(10,HIGH);
  digitalWrite(11,HIGH);
  digitalWrite(12,HIGH);
  digitalWrite(13,HIGH);
  delay(250);
  digitalWrite(12,LOW);
  digitalWrite(13,LOW);
  delay(250);
  digitalWrite(9,LOW);
  digitalWrite(10,LOW);
  delay(250);
  digitalWrite(11,LOW);
  delay(250);
  digitalWrite(9,HIGH);
  digitalWrite(10,HIGH);
  digitalWrite(11,HIGH);
  digitalWrite(12,HIGH);
  digitalWrite(13,HIGH);
  delay(250);
  digitalWrite(11,LOW);
  delay(250);
  digitalWrite(9,LOW);
  digitalWrite(10,LOW);
  delay(250);
  digitalWrite(12,LOW);
  digitalWrite(13,LOW);
  delay(250);
  digitalWrite(9,HIGH);
  digitalWrite(10,HIGH);
  digitalWrite(11,HIGH);
  digitalWrite(12,HIGH);
  digitalWrite(13,HIGH);
  delay(250);
  digitalWrite(11,LOW);
  delay(250);
  digitalWrite(12,LOW);
  digitalWrite(13,LOW);
  delay(250);
  digitalWrite(9,LOW);
  digitalWrite(10,LOW); //FOURTEENTH SERIES END
  delay(250);
  digitalWrite(9,HIGH); //FIFTEENTH SERIES
  digitalWrite(10,HIGH);
  digitalWrite(11,HIGH);
  digitalWrite(12,HIGH);
  digitalWrite(13,HIGH);
  delay(125);
  digitalWrite(9,LOW);
  digitalWrite(10,LOW);
  delay(125);
  digitalWrite(12,LOW);
  digitalWrite(13,LOW);
  delay(125);
  digitalWrite(11,LOW);
  delay(125);
  digitalWrite(9,HIGH);
  digitalWrite(10,HIGH);
  digitalWrite(11,HIGH);
  digitalWrite(12,HIGH);
  digitalWrite(13,HIGH);
  delay(125);
  digitalWrite(12,LOW);
  digitalWrite(13,LOW);
  delay(125);
  digitalWrite(9,LOW);
  digitalWrite(10,LOW);
  delay(125);
  digitalWrite(11,LOW);
  delay(125);
  digitalWrite(9,HIGH);
  digitalWrite(10,HIGH);
  digitalWrite(11,HIGH);
  digitalWrite(12,HIGH);
  digitalWrite(13,HIGH);
  delay(125);
  digitalWrite(11,LOW);
  delay(125);
  digitalWrite(9,LOW);
  digitalWrite(10,LOW);
  delay(125);
  digitalWrite(12,LOW);
  digitalWrite(13,LOW);
  delay(125);
  digitalWrite(9,HIGH);
  digitalWrite(10,HIGH);
  digitalWrite(11,HIGH);
  digitalWrite(12,HIGH);
  digitalWrite(13,HIGH);
  delay(125);
  digitalWrite(11,LOW);
  delay(125);
  digitalWrite(12,LOW);
  digitalWrite(13,LOW);
  delay(125);
  digitalWrite(9,LOW);
  digitalWrite(10,LOW); //FIFTEENTH SERIES END
  delay(350);
}
